name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build-n-push:
    needs: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Declare some docker variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "##[set-output name=imageName;]$(echo kal)"
        echo "::set-output name=IMAGE::${{ steps.vars.outputs.imageName }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build docker image
      run: docker image build -t ghcr.io/orky161/${{ steps.vars.outputs.IMAGE }} .

    - name: Push docker image
      run: docker push ghcr.io/orky161/${{ steps.vars.outputs.IMAGE }}
